SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS equipment;
DROP TABLE IF EXISTS pastCombat;
DROP TABLE IF EXISTS pendingCombat;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS passwordRecover;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS signups;